# Configuration for auto-labeling PRs based on file paths

documentation:
  - changed-files:
    - any-glob-to-any-file:
      - '**/*.md'
      - 'docs/**'
      - 'README.md'
      - 'CLAUDE.md'

python:
  - changed-files:
    - any-glob-to-any-file:
      - '**/*.py'

tests:
  - changed-files:
    - any-glob-to-any-file:
      - 'tests/**'
      - '**/test_*.py'
      - '**/*_test.py'
      - 'pytest.ini'

agent:
  - changed-files:
    - any-glob-to-any-file:
      - 'agent/**'

ingestion:
  - changed-files:
    - any-glob-to-any-file:
      - 'ingestion/**'

database:
  - changed-files:
    - any-glob-to-any-file:
      - 'sql/**'
      - '**/schema.sql'
      - '**/migrations/**'

ci/cd:
  - changed-files:
    - any-glob-to-any-file:
      - '.github/**'
      - '.github/workflows/**'

dependencies:
  - changed-files:
    - any-glob-to-any-file:
      - 'requirements.txt'
      - 'requirements*.txt'
      - 'pyproject.toml'
      - 'setup.py'
      - 'setup.cfg'

docker:
  - changed-files:
    - any-glob-to-any-file:
      - 'Dockerfile'
      - 'docker-compose.yml'
      - '.dockerignore'

configuration:
  - changed-files:
    - any-glob-to-any-file:
      - '.env.example'
      - '**/*.ini'
      - '**/*.cfg'
      - '**/*.toml'
      - '**/*.yml'
      - '**/*.yaml'