services:
  - type: web
    name: marypause-ai
    runtime: python3
    region: oregon  # Specify region for consistent deployment
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
      python verify_deployment.py || echo "Verification completed with warnings"
    startCommand: gunicorn --config gunicorn.conf.py agent.api:app
    plan: free
    autoDeploy: false
    healthCheckPath: /health
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: APP_ENV
        value: production
      - key: APP_HOST
        value: 0.0.0.0
      - key: PORT
        value: 10000
      - key: LOG_LEVEL
        value: INFO
      - key: WEB_CONCURRENCY
        value: 2  # Increased for better performance