# Render deployment configuration for MaryPause AI Medical RAG System
# This file should be read by Render automatically
# If Render ignores this file, the Procfile serves as backup
services:
  - type: web
    name: marypause-ai
    runtime: python3
    region: oregon  # Specify region for consistent deployment
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
      python verify_deployment.py || echo "Verification completed with warnings"
    startCommand: gunicorn --config gunicorn.conf.py agent.api:app
    plan: free
    autoDeploy: false
    healthCheckPath: /health
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: APP_ENV
        value: production
      - key: APP_HOST
        value: 0.0.0.0
      - key: PORT
        value: 10000
      - key: LOG_LEVEL
        value: INFO
      - key: WEB_CONCURRENCY
        value: 2  # Increased for better performance
      # Uvicorn performance optimizations (replaces invalid worker_class_kwargs)
      - key: UVICORN_LOOP
        value: auto  # Let uvicorn choose the best event loop (uvloop if available)
      - key: UVICORN_HTTP
        value: auto  # Let uvicorn choose the best HTTP implementation (httptools if available)
      - key: UVICORN_LIFESPAN
        value: auto  # ASGI lifespan protocol handling